'use strict';

export const FETCH_NEW_RELEASES = 'FETCH_NEW_RELEASES';
export const RECEIVE_NEW_RELEASES = 'RECEIVE_NEW_RELEASES';
export const RECEIVE_ALBUM = 'RECEIVE_ALBUM';
export const RECEIVE_PLAYLISTS = 'RECEIVE_PLAYLISTS';
export const RECEIVE_USERS = 'RECEIVE_USERS';